version: "3.9"

services:
  reco:
    image: ass6:front
    container_name: fastapi-reco
    env_file:
      - .env
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:9000/api/v1/health"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - reco-net

networks:
  reco-net:
    driver: bridge
